// Alle bronnen: APA-vermelding + CRAAP-beoordeling (1 = laag, 5 = hoog)
// letters: C = Currency, R = Relevance, A1 = Authority, A2 = Accuracy, P = Purpose
module.exports = [
 { key:"ACM (z.d.)", apa:"Autoriteit Consument & Markt. (z.d.). *Energieleveranciers met een vergunning*. Geraadpleegd op 6 oktober 2026, van https://www.acm.nl/nl/energie/elektriciteit-en-gas/energie-verkopen/energie-leveren-met-vergunning/energieleveranciers-met-een-vergunning",
   type:"Toezichthouder", s:[4,5,5,5,5],
   C:"De pagina wordt bijgehouden door de ACM, maar heeft geen zichtbare datum; alleen de raadpleegdatum is vast te leggen.", R:"Beantwoordt direct de vraag welke leveranciers er zijn en waarom een vergunning nodig is.", A1:"De ACM is de onafhankelijke toezichthouder en verleent de vergunningen zelf.", A2:"Het is het officiële register; fouten zijn vrijwel uitgesloten.", P:"Puur informeren; geen commercieel belang.",
   con:"Zeer betrouwbaar voor de vergunningplicht en de lijst van leveranciers." },
 { key:"BNNVARA (z.d.)", apa:"BNNVARA. (z.d.). *Steeds meer groene stroom is echt duurzaam opgewekt*. Vroege Vogels. Geraadpleegd op 6 oktober 2026, van https://www.bnnvara.nl/vroegevogels/artikelen/steeds-meer-groene-stroom-is-echt-duurzaam-opgewekt",
   type:"Nieuwsartikel", s:[3,4,3,4,4],
   C:"Geen duidelijke datum op het artikel; het onderzoek van HIER waarover wordt bericht is enkele jaren oud.", R:"Relevant voor de kritiek op vergroening met certificaten bij Eneco en Essent.", A1:"Publieke omroep die verslag doet van onderzoek van klimaatstichting HIER; geen primaire bron.", A2:"Cijfers (34%) komen uit het HIER-onderzoek en worden met reactie van de leveranciers gebracht.", P:"Journalistiek informeren met een milieu-invalshoek.",
   con:"Bruikbaar als secundaire bron; het oorspronkelijke HIER-rapport zou sterker zijn." },
 { key:"CBS (2022)", apa:"Centraal Bureau voor de Statistiek. (2022). *De energierekening in januari 2022: hogere leveringstarieven en lagere belastingen*. https://www.cbs.nl/nl-nl/longread/rapportages/2022/de-energierekening-in-januari-2022-hogere-leveringstarieven-en-lagere-belastingen?onepage=true",
   type:"Statistisch rapport", s:[4,5,5,5,5],
   C:"Gepubliceerd in 2022, precies over de periode die wij beschrijven.", R:"Verklaart waarom het jaar 2022 al met hoge tarieven begon.", A1:"Het CBS is het nationale statistiekbureau.", A2:"Gebaseerd op eigen metingen met uitgebreide technische toelichting.", P:"Neutraal informeren.",
   con:"Zeer betrouwbaar; ideale bron voor de context van januari 2022." },
 { key:"CBS (2023a)", apa:"Centraal Bureau voor de Statistiek. (2023a). *Gemiddelde energietarieven voor consumenten, 2018 - 2023* [Dataset, StatLine-tabel 84672NED]. https://www.cbs.nl/nl-nl/cijfers/detail/84672NED",
   type:"Dataset", s:[4,5,5,5,5],
   C:"De tabel loopt tot 2023 en is daarna stopgezet (opgevolgd door tabel 85592NED), maar voor 2022 is dit de definitieve reeks.", R:"Dit is de dataset achter onze grafiek; precies wat de opdracht vraagt.", A1:"Officiële CBS-statistiek.", A2:"Maandcijfers met vier decimalen en een beschreven methode; let op de methodewijziging in november 2022.", P:"Neutraal; geen belang bij de uitkomst.",
   con:"De sterkste bron van dit rapport; wel de methodebreuk vermelden." },
 { key:"CBS (2023b)", apa:"Centraal Bureau voor de Statistiek. (2023b). *Energierekening 37 procent hoger*. https://www.cbs.nl/nl-nl/nieuws/2023/29/energierekening-37-procent-hoger",
   type:"Nieuwsbericht CBS", s:[4,5,5,5,5],
   C:"Uit juli 2023, met terugblik op heel 2022.", R:"Beschrijft de vertraging tussen groothandelsprijs en consumententarief.", A1:"CBS.", A2:"Gebaseerd op dezelfde dataset als onze grafiek.", P:"Neutraal informeren.",
   con:"Betrouwbaar en goed bruikbaar voor de verklaring van de piek in het najaar." },
 { key:"CBS (2024)", apa:"Centraal Bureau voor de Statistiek. (2024). *De energierekening januari 2024*. https://www.cbs.nl/nl-nl/longread/diversen/2024/de-energierekening-januari-2024?onepage=true",
   type:"Statistisch rapport", s:[4,4,5,5,5],
   C:"Uit 2024, beschrijft het prijsplafond van 2023.", R:"Alleen gebruikt voor het prijsplafond en de korting van € 190.", A1:"CBS.", A2:"Cijfers met technische toelichting.", P:"Neutraal.",
   con:"Betrouwbaar; beperkt gebruikt." },
 { key:"CBS (2025a)", apa:"Centraal Bureau voor de Statistiek. (2025a). *Energieverbruik uit hernieuwbare bronnen stijgt naar 20 procent*. https://www.cbs.nl/nl-nl/nieuws/2025/23/energieverbruik-uit-hernieuwbare-bronnen-stijgt-naar-20-procent",
   type:"Nieuwsbericht CBS", s:[5,5,5,5,5],
   C:"Juni 2025, over verslagjaar 2024: de meest recente definitieve cijfers.", R:"Kerncijfers voor de duurzaamheidsontwikkelingen.", A1:"CBS.", A2:"Officiële statistiek hernieuwbare energie.", P:"Neutraal.",
   con:"Zeer betrouwbaar." },
 { key:"CBS (2025b)", apa:"Centraal Bureau voor de Statistiek. (2025b). *Steeds meer woningen aardgasvrij*. https://www.cbs.nl/nl-nl/nieuws/2025/50/steeds-meer-woningen-aardgasvrij",
   type:"Nieuwsbericht CBS", s:[5,5,5,5,5],
   C:"December 2025, over 2024.", R:"Beantwoordt direct de vraag in hoeverre Nederland van het gas af is.", A1:"CBS.", A2:"Gebaseerd op registraties van netbeheerders en woningkenmerken.", P:"Neutraal.",
   con:"Zeer betrouwbaar; de kernbron voor paragraaf 4.4." },
 { key:"Consumentenbond (2022)", apa:"Consumentenbond. (2022). *Energieleveranciers moeten btw-verlaging direct doorberekenen*. https://www.consumentenbond.nl/nieuws/2022/energieleveranciers-moeten-btw-verlaging-direct-doorberekenen",
   type:"Nieuwsbericht belangenorganisatie", s:[4,4,4,4,3],
   C:"Uit 2022, over de btw-verlaging per 1 juli 2022.", R:"Onderbouwt een van de oorzaken van de schommelingen.", A1:"De Consumentenbond is een bekende, onafhankelijke consumentenorganisatie.", A2:"Feitelijk juist, maar beknopt.", P:"Informeren én opkomen voor consumenten; kleurt de toon.",
   con:"Goed bruikbaar voor het feit van de btw-verlaging." },
 { key:"Duurzaam Ondernemen (2026)", apa:"Duurzaam Ondernemen. (2026). *Wachtlijst netcongestie groeit naar ruim 15.000 bedrijven, batterijopslag verdubbelt*. https://www.duurzaam-ondernemen.nl/wachtlijst-netcongestie-groeit-naar-ruim-15-000-bedrijven-batterijopslag-verdubbelt/",
   type:"Vakmedium", s:[5,5,3,4,3],
   C:"Uit 2026, over de cijfers van eind 2025.", R:"Bevat de actuele wachtlijstcijfers die wij nodig hadden.", A1:"Vakmedium dat de cijfers van Netbeheer Nederland overneemt; geen primaire bron.", A2:"Cijfers komen overeen met het bericht van Netbeheer Nederland.", P:"Informeren over duurzaam ondernemen; mogelijk gesponsorde inhoud.",
   con:"Bruikbaar, maar de cijfers zijn gecontroleerd bij Netbeheer Nederland." },
 { key:"Enerdata (2022)", apa:"Enerdata. (2022). *Russia will halt gas supplies to Europe via Nord Stream 1 for 3 days for repairs*. https://www.enerdata.net/publications/daily-energy-news/russia-will-halt-gas-europe-nord-stream-1-3-days-repairs.html",
   type:"Energie-analist", s:[4,4,4,4,4],
   C:"Augustus 2022, precies op het moment van de piek.", R:"Onderbouwt de reductie en sluiting van Nord Stream 1.", A1:"Internationaal onderzoeksbureau voor energiedata.", A2:"Concrete hoeveelheden (mcm/d) en data.", P:"Informeren; verkoopt ook betaalde data.",
   con:"Betrouwbaar voor de feiten rond Nord Stream 1." },
 { key:"Energie-Nederland (2024)", apa:"Energie-Nederland. (2024). *Opbouw energierekening 2025* [Infographic]. https://www.energie-nederland.nl/wp-content/uploads/2024/04/Opbouw-energierekening-2025-infographic-E-NL.pdf",
   type:"Brancheorganisatie", s:[4,5,4,4,3],
   C:"Uit 2024, over 2025.", R:"Laat precies de vier onderdelen van de energierekening zien.", A1:"Brancheorganisatie van de leveranciers; deskundig maar partij.", A2:"Gebaseerd op officiële tarieven.", P:"Informeren én het eigen aandeel in de rekening klein laten lijken.",
   con:"Goed voor de opbouw; percentages met enige voorzichtigheid gebruiken." },
 { key:"Energievergelijk (2025)", apa:"Energievergelijk. (2025). *Meest duurzame energieleveranciers van Nederland volgens nieuw onderzoek (2025)*. https://www.energievergelijk.nl/nieuws/meest-duurzame-energieleveranciers-van-nederland-volgens-nieuw-onderzoek-2025",
   type:"Vergelijkingssite", s:[5,4,2,3,2],
   C:"Uit 2025, gebaseerd op de stroometiketten 2025.", R:"Geeft een actueel beeld van de groenste leveranciers.", A1:"Commerciële vergelijkingssite, geen onafhankelijk onderzoeksinstituut.", A2:"Gebaseerd op stroometiketten, maar de methode is niet volledig beschreven.", P:"Verdient aan overstappers; belang bij het promoten van leveranciers.",
   con:"Alleen gebruikt als aanvulling op de onafhankelijke ranking." },
 { key:"Energyzero (z.d.)", apa:"Energyzero. (z.d.). *Wie is mijn regionale netbeheerder?* Geraadpleegd op 6 oktober 2026, van https://support.energyzero.nl/hc/nl/articles/360001200178-Wie-is-mijn-regionale-netbeheerder",
   type:"Servicepagina leverancier", s:[3,4,3,4,3],
   C:"Geen datum; de indeling in netbeheerders verandert zelden.", R:"Geeft een compact overzicht van alle netbeheerders en hun gebieden.", A1:"Een leverancier, niet de netbeheerders zelf.", A2:"Klopt met de informatie van de netbeheerders zelf.", P:"Klantenservice; geen belang bij de inhoud.",
   con:"Bruikbaar als overzicht; feiten zijn eenvoudig controleerbaar." },
 { key:"Engie (2026)", apa:"Engie. (2026). *Bijmengverplichting groen gas: stand van zaken*. https://www.engie.nl/zakelijk/kennisbank/blogs/2026-03-bijmengverplichting-groen-gas-stand-van-zaken",
   type:"Kennisbank leverancier", s:[5,5,3,4,3],
   C:"Maart 2026, de meest actuele stand van het wetsvoorstel.", R:"Beschrijft de bijmengverplichting en de hoeveelheden per jaar.", A1:"Leverancier die zelf onder de verplichting valt; deskundig maar belanghebbend.", A2:"Cijfers komen overeen met het wetsvoorstel in de Tweede Kamer.", P:"Zakelijke klanten informeren en binden.",
   con:"Bruikbaar; cijfers gecontroleerd met Vattenfall (z.d.) en het wetsvoorstel." },
 { key:"Enexis Groep (2025)", apa:"Enexis Groep. (2025). *Enexis investeert 7 miljard euro in drie jaar in grootste uitbreiding regionale energienet ooit*. https://www.enexisgroep.nl/nieuws/enexis-investeert-7-miljard-euro-in-drie-jaar-in-grootste-uitbreiding-regionale-energienet-ooit/",
   type:"Persbericht", s:[5,5,5,4,3],
   C:"2025.", R:"Direct over de investeringen van onze organisatie.", A1:"Enexis zelf.", A2:"Concrete bedragen; niet extern gecontroleerd.", P:"Positief nieuws over de eigen organisatie.",
   con:"Betrouwbaar voor de feiten, formuleren als 'Enexis stelt dat'." },
 { key:"Enexis Groep (2026)", apa:"Enexis Groep. (2026). *Enexis realiseert recorduitbreiding elektriciteitsnet, maar toekomst vraagt om meer flexibele oplossingen*. https://www.enexisgroep.nl/nieuws/enexis-realiseert-recorduitbreiding-elektriciteitsnet-maar-toekomst-vraagt-om-meer-flexibele-oplossingen/",
   type:"Persbericht", s:[5,5,5,4,3],
   C:"2026, over het jaar 2025.", R:"Bevat de cijfers over netcapaciteit, flexibiliteit en investeringen in 2025.", A1:"Enexis zelf.", A2:"Cijfers sluiten aan op het jaarverslag 2025.", P:"Verantwoorden en profileren.",
   con:"Betrouwbaar; de toon is positief, de cijfers zijn bruikbaar." },
 { key:"Enexis Groep (z.d.)", apa:"Enexis Groep. (z.d.). *Privacyverklaring klanten & zakelijke relaties*. Geraadpleegd op 6 oktober 2026, van https://www.enexisgroep.nl/privacy/klanten-en-zakelijke-relaties/",
   type:"Privacyverklaring", s:[4,4,5,5,4],
   C:"Wordt bijgehouden bij wetswijzigingen; geen vaste datum.", R:"Laat zien hoe Enexis met persoonsgegevens en datalekken omgaat.", A1:"Enexis zelf, de verwerkingsverantwoordelijke.", A2:"Juridisch document, verplicht correct.", P:"Wettelijke informatieplicht.",
   con:"Betrouwbaar als beschrijving van het beleid, niet als bewijs van naleving." },
 { key:"Enexis Holding N.V. (2026)", apa:"Enexis Holding N.V. (2026). *Jaarverslag 2025*. https://www.enexisgroep.nl/media/ugahs4is/jaarverslag-2025-enexis-holding-nv.pdf",
   type:"Jaarverslag", s:[5,5,5,5,4],
   C:"Meest recente volledige verslagjaar.", R:"Organisatiegegevens van Enexis die wij in sprint 1 al gebruikten.", A1:"Officiële publicatie met accountantscontrole.", A2:"Controleerbare cijfers.", P:"Verantwoorden en profileren.",
   con:"Zeer betrouwbare primaire bron (zie ook ons sprint 1-rapport)." },
 { key:"Enexis Netbeheer (z.d.)", apa:"Enexis Netbeheer. (z.d.). *Slimme meter: privacy en uw gegevens*. Geraadpleegd op 6 oktober 2026, van https://www.enexis.nl/meter/slimme-meter/uw-privacy-en-gegevens",
   type:"Klantpagina", s:[4,5,5,4,4],
   C:"Geen datum, wordt bijgehouden.", R:"Direct relevant voor de AVG en de slimme-meterdata uit ons datavraagstuk.", A1:"Enexis is de partij die de meters uitleest.", A2:"Beschrijft de regels (toestemming, standaard uitlezen) correct.", P:"Klanten informeren en geruststellen.",
   con:"Goed bruikbaar." },
 { key:"Essent (2025)", apa:"Essent. (2025). *Stroometiket 2025*. https://www.essent.nl/-/media/essent/documenten/stroometiket/essent-stroometiket-2025.pdf",
   type:"Stroometiket (wettelijk)", s:[5,5,5,5,4],
   C:"Over leveringsjaar 2025.", R:"Toont de herkomst van de stroom van Essent, de kern van onze beoordeling.", A1:"Essent zelf, maar het stroometiket is wettelijk verplicht en gestandaardiseerd.", A2:"Percentages op basis van Garanties van Oorsprong.", P:"Wettelijke verplichting; wel zo gunstig mogelijk gepresenteerd (aparte 'retail-mix').",
   con:"Betrouwbaar voor de cijfers; de totale mix zegt meer dan de retail-mix." },
 { key:"Greenpeace et al. (2022)", apa:"Greenpeace, Consumentenbond, Natuur & Milieu & WISE. (2022). *Groene Stroom Ranglijst*. https://www.greenpeace.org/nl/kom-in-actie/groene-stroom-ranglijst/",
   type:"Onafhankelijk onderzoek", s:[3,5,4,4,3],
   C:"De laatste volledige ranglijst dateert uit 2022; er is geen recentere editie met dezelfde methode.", R:"Precies de vergelijking van leveranciers die de opdracht vraagt.", A1:"Vier bekende organisaties met een vaste methode (investeringen, inkoop, levering).", A2:"Transparante methode, maar scores verouderen.", P:"Consumenten sturen naar groene leveranciers; milieuorganisaties zijn partij.",
   con:"Beste beschikbare vergelijking; actualiteit is het zwakke punt, daarom aangevuld met stroometiketten 2025." },
 { key:"Keuze.nl (z.d.)", apa:"Keuze.nl. (z.d.). *Dit zijn de grootste energieleveranciers van Nederland*. Geraadpleegd op 6 oktober 2026, van https://www.keuze.nl/nieuws/dit-zijn-de-grootste-energieleveranciers-van-nederland",
   type:"Vergelijkingssite", s:[3,4,2,3,2],
   C:"Geen duidelijke datum; klantaantallen veranderen jaarlijks.", R:"Geeft de klantaantallen van de grootste leveranciers.", A1:"Commerciële vergelijkingssite.", A2:"Afgeronde aantallen zonder bronvermelding.", P:"Verdient aan overstappen.",
   con:"Alleen gebruikt voor globale klantaantallen ('circa')." },
 { key:"Ministerie van Klimaat en Groene Groei (2025)", apa:"Ministerie van Klimaat en Groene Groei. (2025). *Klimaat- en Energienota 2025*. Tweede Kamer der Staten-Generaal. https://www.tweedekamer.nl/downloads/document?id=2025D39522",
   type:"Beleidsdocument", s:[5,5,5,4,3],
   C:"2025.", R:"Bevat de doelen voor wind op zee, groen gas en warmte.", A1:"De Rijksoverheid.", A2:"Beleidscijfers; deels ambities in plaats van gerealiseerde feiten.", P:"Verantwoording aan de Kamer; presenteert beleid positief.",
   con:"Betrouwbaar voor doelen en stand van zaken." },
 { key:"Netbeheer Nederland (z.d.)", apa:"Netbeheer Nederland. (z.d.). *Wachtlijsten nemen toe*. Geraadpleegd op 6 oktober 2026, van https://www.netbeheernederland.nl/artikelen/nieuws/wachtlijsten-nemen-toe",
   type:"Brancheorganisatie", s:[5,5,4,4,3],
   C:"Actueel, over eind 2025.", R:"Primaire bron van de wachtlijstcijfers.", A1:"Brancheorganisatie van de netbeheerders, gebaseerd op hun gezamenlijke data; Enexis is zelf lid.", A2:"Cijfers uit de eigen registraties van de netbeheerders.", P:"Informeren én de belangen van de sector agenderen.",
   con:"Sterk voor cijfers; niet onafhankelijk." },
 { key:"NOS (2024)", apa:"NOS. (2024). *Steeds meer bedrijven melden datalek bij klantcommunicatiebureau AddComm*. https://nos.nl/l/2522386",
   type:"Nieuwsartikel", s:[4,5,4,4,5],
   C:"Mei/juni 2024, direct na het incident.", R:"Beschrijft het AddComm-lek en de getroffen organisaties.", A1:"Publieke omroep met journalistieke standaarden.", A2:"Feiten komen overeen met de berichten van de bedrijven zelf.", P:"Neutraal informeren.",
   con:"Betrouwbaar." },
 { key:"Overstappen.nl (2025)", apa:"Overstappen.nl. (2025). *ACM heeft goed nieuws: financiële gezondheid van Nederlandse energieleveranciers is verbeterd*. https://www.overstappen.nl/nieuws/acm-heeft-goed-nieuws-financiele-gezondheid-van-nederlandse-energieleveranciers-is-verbeterd/",
   type:"Vergelijkingssite", s:[5,4,2,4,2],
   C:"2025.", R:"Geeft het aantal vergunninghouders in 2025.", A1:"Commerciële site die een ACM-rapport samenvat.", A2:"Cijfers komen uit het ACM-rapport.", P:"Verdient aan overstappen.",
   con:"Alleen gebruikt voor het aantal vergunningen; liever het ACM-rapport zelf." },
 { key:"PBL (2024)", apa:"Planbureau voor de Leefomgeving. (2024). *Hoe naar een aardgasvrije gebouwde omgeving in 2050?* https://www.pbl.nl/downloads/pbl-2024-hoe-naar-een-aardgasvrije-gebouwde-omgeving-in-2050-5504.pdf",
   type:"Onderzoeksrapport", s:[4,5,5,5,5],
   C:"2024.", R:"Analyseert precies het tempo van de warmtetransitie.", A1:"Onafhankelijk planbureau van de Rijksoverheid.", A2:"Wetenschappelijke methode met scenario's.", P:"Onafhankelijk adviseren.",
   con:"Zeer betrouwbaar." },
 { key:"Pure Energie (z.d.-a)", apa:"Pure Energie. (z.d.-a). *Jaaroverzicht schommelende gasprijzen*. Geraadpleegd op 6 oktober 2026, van https://pure-energie.nl/over-ons/nieuws/jaaroverzicht-schommelende-gasprijzen/",
   type:"Nieuwsblog leverancier", s:[3,4,3,3,3],
   C:"Geen datum zichtbaar; beschrijft 2022.", R:"Chronologisch overzicht van de gebeurtenissen in 2022.", A1:"Een leverancier, geen analist.", A2:"Globaal juist, maar zonder bronvermelding.", P:"Klanten informeren en eigen stabiliteit benadrukken.",
   con:"Alleen gebruikt voor de chronologie, naast sterkere bronnen." },
 { key:"Pure Energie (z.d.-b)", apa:"Pure Energie. (z.d.-b). *Al 9 jaar op rij de groenste leverancier*. Geraadpleegd op 6 oktober 2026, van https://pure-energie.nl/over-ons/nieuws/groenste-energieleverancier/",
   type:"Nieuwsblog leverancier", s:[4,4,3,4,2],
   C:"Verwijst naar de meest recente ranglijst.", R:"Beschrijft wat Pure Energie doet op duurzaamheid.", A1:"De leverancier over zichzelf.", A2:"Score klopt met de onafhankelijke ranglijst.", P:"Reclame: de score wordt gebruikt om klanten te werven.",
   con:"Bruikbaar als illustratie; de score is gecontroleerd bij Greenpeace et al. (2022)." },
 { key:"Rijksoverheid (2022)", apa:"Rijksoverheid. (2022). *Update gasleveringszekerheid 8 - 26 augustus 2022*. https://www.rijksoverheid.nl/onderwerpen/gas/documenten/publicaties/2022/08/26/update-gasleveringszekerheid-8---26-augustus-2022",
   type:"Overheidspublicatie", s:[4,4,5,5,5],
   C:"26 augustus 2022, op het hoogtepunt van de crisis.", R:"Geeft de vulgraad van de gasopslag.", A1:"Ministerie van EZK.", A2:"Officiële cijfers.", P:"Neutraal informeren.",
   con:"Zeer betrouwbaar." },
 { key:"Rijksoverheid (z.d.)", apa:"Rijksoverheid. (z.d.). *Overstap naar duurzame warmtebronnen*. Geraadpleegd op 6 oktober 2026, van https://www.rijksoverheid.nl/onderwerpen/duurzame-energie/duurzame-warmtebronnen",
   type:"Overheidswebsite", s:[4,5,5,4,4],
   C:"Wordt bijgehouden; geen datum.", R:"Beschrijft de doelen voor aardgasvrij in 2030 en 2050.", A1:"Rijksoverheid.", A2:"Beleidsdoelen correct weergegeven.", P:"Informeren en beleid uitleggen.",
   con:"Betrouwbaar voor de doelstellingen." },
 { key:"RVO (2022)", apa:"Rijksdienst voor Ondernemend Nederland. (2022). *Aardgasvrije gebouwde omgeving: de realisatie en beïnvloedende factoren*. https://www.rvo.nl/files/file/2022-11/74812-RVO-Aardgasvrij-2022-PDF-UA.pdf",
   type:"Onderzoeksrapport", s:[3,5,5,5,4],
   C:"November 2022; de stand van zaken is inmiddels ingehaald door CBS (2025b).", R:"Bevat de concrete doelen (1,5 miljoen, 2,3 miljoen, corporaties).", A1:"Uitvoeringsorganisatie van de Rijksoverheid.", A2:"Goed onderbouwd rapport.", P:"Informeren en beleid ondersteunen.",
   con:"Betrouwbaar voor de doelen; voor de stand van zaken recentere CBS-cijfers gebruikt." },
 { key:"Security.NL (2021)", apa:"Security.NL. (2021). *Eneco meldt datalek na aanval met hergebruikte wachtwoorden*. https://www.security.nl/posting/685592/Eneco+meldt+datalek+na+aanval+met+hergebruikte+wachtwoorden",
   type:"Vaknieuws", s:[4,5,4,4,4],
   C:"Januari 2021, direct na het incident.", R:"Beschrijft het eerste privacy-incident bij Eneco.", A1:"Gespecialiseerde beveiligingsnieuwssite, veel gebruikt in de sector.", A2:"Gebaseerd op de verklaring van Eneco zelf.", P:"Informeren van beveiligingsprofessionals.",
   con:"Betrouwbaar." },
 { key:"Security.NL (2024a)", apa:"Security.NL. (2024a). *Essent en Vattenfall waarschuwen klanten voor datalek bij AddComm*. https://www.security.nl/posting/842955/Essent+en+Vattenfall+waarschuwen+klanten+voor+datalek+bij+AddComm",
   type:"Vaknieuws", s:[4,4,4,4,4],
   C:"Mei 2024.", R:"Laat zien dat het AddComm-lek de hele sector raakte.", A1:"Gespecialiseerde nieuwssite.", A2:"Gebaseerd op de waarschuwingen van de bedrijven.", P:"Informeren.",
   con:"Betrouwbaar." },
 { key:"Security.NL (2024b)", apa:"Security.NL. (2024b). *Eneco waarschuwt klanten voor datalek bij AddComm*. https://www.security.nl/posting/843489/Eneco+waarschuwt+klanten+voor+datalek+bij+AddComm",
   type:"Vaknieuws", s:[4,5,4,4,4],
   C:"Mei 2024.", R:"Beschrijft het tweede privacy-incident bij Eneco.", A1:"Gespecialiseerde nieuwssite.", A2:"Gebaseerd op de verklaring van Eneco.", P:"Informeren.",
   con:"Betrouwbaar." },
 { key:"Selectra (z.d.)", apa:"Selectra. (z.d.). *Energierekening: opbouw en kosten*. Geraadpleegd op 6 oktober 2026, van https://selectra.nl/energie/energierekening",
   type:"Vergelijkingssite", s:[4,5,2,4,2],
   C:"Bevat de tarieven van 2026, dus actueel.", R:"Legt de vier onderdelen van de energierekening helder uit.", A1:"Commerciële vergelijkingssite.", A2:"Tarieven komen overeen met de Belastingdienst.", P:"Verdient aan overstappen.",
   con:"Bruikbaar voor de uitleg; tarieven bij voorkeur bij de Belastingdienst controleren." },
 { key:"Solar Magazine (2025)", apa:"Solar Magazine. (2025). *Zonnepanelen goed voor 20 procent van Nederlandse stroomproductie*. https://solarmagazine.nl/nieuws-zonne-energie/i39386/zonnepanelen-goed-voor-20-procent-van-nederlandse-stroomproductie",
   type:"Vakmedium", s:[5,4,3,4,3],
   C:"2025, over 2024.", R:"Aandeel zonnestroom als oorzaak van overcapaciteit.", A1:"Vakblad voor de zonne-energiesector; neemt CBS-cijfers over.", A2:"Cijfer klopt met CBS.", P:"Informeren én de sector promoten.",
   con:"Bruikbaar; cijfer is CBS-gebaseerd." },
 { key:"Solar Magazine (2026a)", apa:"Solar Magazine. (2026a). *75 procent meer uren met negatieve stroomprijzen, nieuw record Nederland en België*. https://solarmagazine.nl/nieuws-zonne-energie/i40983/75-procent-meer-uren-met-negatieve-stroomprijzen-nieuw-record-nederland-en-belgie",
   type:"Vakmedium", s:[5,5,3,4,3],
   C:"2026, over heel 2025.", R:"Bevat de reeks negatieve prijsuren 2022-2025.", A1:"Vakblad; gebaseerd op marktdata van de beurs.", A2:"Concrete uurcijfers, controleerbaar bij EPEX.", P:"Informeren én de sector promoten.",
   con:"Bruikbaar." },
 { key:"Solar Magazine (2026b)", apa:"Solar Magazine. (2026b). *Enexis kondigt nieuwe netknelpunten aan op stroomnet Limburg en Drenthe*. https://solarmagazine.nl/nieuws-zonne-energie/i43250/enexis-kondigt-nieuwe-netknelpunten-aan-op-stroomnet-limburg-en-drenthe",
   type:"Vakmedium", s:[5,5,3,4,3],
   C:"Maart 2026.", R:"Beschrijft waar in het Enexis-gebied congestie speelt.", A1:"Vakblad dat de updates van Enexis overneemt.", A2:"Komt overeen met de netcapaciteitsupdates van Enexis.", P:"Informeren van de sector.",
   con:"Bruikbaar; primaire bron zijn de updates van Enexis zelf." },
 { key:"Vattenfall (z.d.)", apa:"Vattenfall. (z.d.). *Bijmengverplichting groen gas: de gevolgen*. Geraadpleegd op 6 oktober 2026, van https://www.vattenfall.nl/grootzakelijk/energiemarkt/wet-en-regelgeving/bijmengverplichting/",
   type:"Kennisbank leverancier", s:[4,4,3,4,3],
   C:"Wordt bijgehouden; geen datum.", R:"Tweede bron voor de bijmengverplichting.", A1:"Leverancier die onder de regeling valt.", A2:"Komt overeen met Engie (2026).", P:"Zakelijke klanten informeren.",
   con:"Bruikbaar als controlebron." },
 { key:"Verordening (EU) 2016/679 (2016)", apa:"Verordening (EU) 2016/679 van het Europees Parlement en de Raad van 27 april 2016 betreffende de bescherming van natuurlijke personen in verband met de verwerking van persoonsgegevens (Algemene verordening gegevensbescherming). (2016). *Publicatieblad van de Europese Unie, L 119*, 1-88.",
   type:"Wetgeving", s:[5,5,5,5,5],
   C:"Van kracht sinds 25 mei 2018 en ongewijzigd.", R:"De wet waarop de privacyvraag is gebaseerd.", A1:"Europese wetgever.", A2:"De wettekst zelf.", P:"Wetgeving.",
   con:"Primaire bron; hoogste betrouwbaarheid." },
 { key:"WISE (z.d.)", apa:"WISE. (z.d.). *Deel stroomleveranciers blijft 'greenwashen', politiek moet ingrijpen*. Geraadpleegd op 6 oktober 2026, van https://wisenederland.nl/deel-stroomleveranciers-blijft-greenwashen-politiek-moet-ingrijpen/",
   type:"Milieuorganisatie", s:[3,5,4,4,3],
   C:"Geen datum zichtbaar; de scores (Eneco 8,1, Essent 4,8, Vattenfall 4,3) komen uit een eerdere editie van de Stroomranking.", R:"Bevat de scores die wij voor de drie leveranciers gebruiken.", A1:"Mede-uitvoerder van de Stroomranking.", A2:"Scores volgens vaste methode.", P:"Milieuorganisatie met een duidelijk standpunt (anti-greenwashing).",
   con:"Bruikbaar voor de scores; het standpunt is herkenbaar en daarom benoemd." },
];
