// Deel 2: hoofdstukken 4 t/m 6
const L = require("./lib.js");
const { P, H1, H2, H3, Bullet, Num, Caption, Conclusie, table } = L;

module.exports = function deel2() {
  const out = [];

  // ---------- 4. Duurzaamheid
  out.push(H1("4. Duurzaamheid"));
  out.push(P("De energiemarkt verandert snel door de energietransitie. In dit hoofdstuk beschrijven we de belangrijkste duurzaamheidsontwikkelingen op het gebied van gas en elektriciteit, vergelijken we drie energieleveranciers op duurzaamheid en kijken we naar de doelstellingen en de stand van zaken van \"Nederland van het gas af\"."));

  out.push(H2("4.1 Duurzaamheidsontwikkelingen op het gebied van gas en elektriciteit"));
  out.push(H3("Ontwikkeling 1: steeds meer hernieuwbare elektriciteit"));
  out.push(P("Het aandeel hernieuwbare energie in het totale energieverbruik steeg in 2024 naar 19,8%, tegen 17,4% in 2023. De grootste bron is biomassa (34%), gevolgd door windenergie (32%) en zonne-energie (22%). Bij elektriciteit gaat het nog sneller: in 2024 kwam 50% van het elektriciteitsverbruik uit hernieuwbare bronnen, tegen 46% een jaar eerder. De productie van windmolens steeg (gecorrigeerd voor de hoeveelheid wind) met 20%, vooral door nieuwe windparken op zee, en de productie van zonnestroom met 9% (CBS, 2025a). Voor netbeheerders betekent dit dat de stroom steeds vaker van veel kleine, weersafhankelijke bronnen komt in plaats van van een paar grote centrales."));
  out.push(H3("Ontwikkeling 2: wind op zee als ruggengraat"));
  out.push(P("Het kabinet werkt aan 21 gigawatt (GW) windenergie op zee rond 2032. Inmiddels staat er 4,7 GW, is 1,5 GW in aanbouw en is 4 GW al vergund. TenneT werkt aan de aansluitingen van deze windparken op het landelijke net (Ministerie van Klimaat en Groene Groei, 2025). Wind op zee moet de basis worden van een elektriciteitssysteem zonder gascentrales en is daarmee de belangrijkste ontwikkeling voor de productiekant."));
  out.push(H3("Ontwikkeling 3: groen gas en de bijmengverplichting"));
  out.push(P("Aardgas wordt niet alleen vervangen door elektriciteit, maar ook deels vergroend. Groen gas wordt gemaakt door biogas uit mest, rioolslib en gft-afval op te waarderen tot aardgaskwaliteit, zodat het gewoon door het bestaande gasnet kan. In 2025 steeg de productie van groen gas in Nederland naar 0,33 miljard m³ (Ministerie van Klimaat en Groene Groei, 2025). Om de vraag te vergroten behandelt de Tweede Kamer het wetsvoorstel *Wet bijmengverplichting groen gas*: leveranciers moeten vanaf 2027 een steeds groter deel groen gas bijmengen, oplopend van ongeveer 0,16 miljard m³ in 2027 naar 0,84 miljard m³ in 2031. Ook buitenlands groen gas mag meetellen (Engie, 2026; Vattenfall, z.d.). Daarnaast wordt gewerkt aan waterstof als vervanger van aardgas in de industrie. Voor een netbeheerder als Enexis is dit belangrijk: het gasnet blijft nog lang nodig, maar vervoert in de toekomst een ander gas."));
  out.push(H3("Ontwikkeling 4: warmtetransitie in de gebouwde omgeving"));
  out.push(P("Woningen gaan over van cv-ketel op gas naar (hybride) warmtepompen en warmtenetten. Sinds 1 juli 2018 worden geen bouwvergunningen meer afgegeven voor nieuwbouw met een gasaansluiting, waardoor het aandeel aardgasvrije woningen vanzelf groeit (CBS, 2025b). Met de Wet collectieve warmte zet het kabinet een belangrijke stap voor duurzame warmtenetten, waarbij gemeenten en publieke partijen meer regie krijgen (Ministerie van Klimaat en Groene Groei, 2025). Elk huishouden dat van het gas gaat, vraagt wel een zwaardere elektriciteitsaansluiting; de warmtetransitie verschuift de druk dus van het gasnet naar het elektriciteitsnet."));
  out.push(H3("Ontwikkeling 5: flexibiliteit, opslag en slimme contracten"));
  out.push(P("Omdat zon en wind niet te sturen zijn, verschuift de aandacht naar het sturen van de vraag. Batterijen slaan het middagoverschot op (het aantal opslagcontracten bij netbeheerders verdubbelde naar 237), bedrijven sluiten flexibele contracten en consumenten kiezen steeds vaker een dynamisch contract met uurprijzen (Duurzaam Ondernemen, 2026). Het record van 581 uren met negatieve stroomprijzen in 2025 laat zien hoe hard deze flexibiliteit nodig is (Solar Magazine, 2026a). Dit is ook de ontwikkeling waar data de grootste rol speelt: zonder meetdata per kwartier kun je vraag en aanbod niet op elkaar afstemmen."));

  out.push(H2("4.2 Drie energieleveranciers vergeleken op duurzaamheid"));
  out.push(P("Om leveranciers eerlijk te vergelijken hebben we gebruikgemaakt van onafhankelijk onderzoek. Consumentenbond, Natuur & Milieu, WISE en Greenpeace beoordelen leveranciers jaarlijks op drie onderdelen: investeringen, inkoop en levering van stroom. Een leverancier die stroom inkoopt op de grijze markt en die alleen op papier vergroent met buitenlandse certificaten (Garanties van Oorsprong) scoort laag; een leverancier die zelf in Nederlandse wind- en zonneparken investeert scoort hoog (Greenpeace et al., 2022; WISE, z.d.). Daarnaast hebben we de stroometiketten 2025 en de analyse van Energievergelijk (2025) gebruikt. We hebben één slechte, één gemiddelde en één goede leverancier gekozen."));
  out.push(H3("Slecht: Essent"));
  out.push(P("Essent is met 1,5 miljoen klanten de op één na grootste leverancier, maar scoort in de duurzaamheidsranking van Consumentenbond, Natuur & Milieu en WISE een onvoldoende: een 4,8 (WISE, z.d.). In de Groene Stroom Ranglijst van Greenpeace presteert moederbedrijf RWE/Essent van alle bedrijven in Nederland het slechtst, met een 3, omdat het nog investeerde in kolencentrales en de bijstook van biomassa meerekende als groene energie (Greenpeace et al., 2022). Het stroometiket 2025 laat de kern van het probleem zien: de totale mix van Essent N.V. bestond in 2025 voor 12% uit aardgas, 54,5% uit 'vergroende' stroom uit het buitenland en maar 33,5% uit groene stroom uit Nederland (Essent, 2025). Consumenten krijgen op papier 100% groene stroom, maar dat komt grotendeels door buitenlandse certificaten. Essent is sinds de overname door E.ON wel bezig met verbetering, maar loopt duidelijk achter op de kleinere groene leveranciers."));
  out.push(H3("Gemiddeld: Eneco"));
  out.push(P("Eneco scoort in dezelfde ranking een 8,1; het was de eerste keer in zeven jaar dat één van de 'grote drie' zo hoog scoorde (WISE, z.d.). Volgens het stroometiket komt 97,5% van de stroom van Eneco uit Nederlandse bronnen (Energievergelijk, 2025). Eneco investeert zelf in wind- en zonneparken en in warmtenetten. Toch noemen we Eneco 'gemiddeld' en niet 'goed': uit onderzoek van klimaatstichting HIER blijkt dat 34% van de onderzochte groenestroomproducten niet van duurzame bronnen in Nederland komt maar wordt vergroend met buitenlandse certificaten, en daarbij gaat het onder meer om bepaalde producten van Eneco en Essent (BNNVARA, z.d.). Eneco is bovendien veel groter dan de koplopers, waardoor een deel van het aanbod nog op de grijze markt wordt ingekocht. Eneco doet het dus goed voor een grote leverancier, maar is niet de groenste keuze."));
  out.push(H3("Goed: Pure Energie"));
  out.push(P("Pure Energie uit Enschede scoort al negen jaar op rij een 10 en is daarmee de groenste leverancier van Nederland (Greenpeace et al., 2022; Pure Energie, z.d.-b). Het bedrijf levert uitsluitend stroom uit eigen windmolens en zonneparken in Nederland en investeert de winst in nieuwe parken. Er wordt dus geen grijze stroom ingekocht die achteraf wordt vergroend. Ook Energie VanOns en OM | Nieuwe Energie behalen een 10; Vandebron, Greenchoice en OM worden in de analyse van Energievergelijk (2025) genoemd als de drie meest duurzame leveranciers van 2025, omdat zij uitsluitend groene stroom van Nederlandse herkomst leveren en het gas compenseren of mengen met groen gas. Het nadeel van deze koplopers is hun omvang: samen hebben zij een klein marktaandeel, waardoor hun invloed op de totale Nederlandse stroommix beperkt is."));
  out.push(table(
    ["", "Essent (slecht)", "Eneco (gemiddeld)", "Pure Energie (goed)"],
    [
      ["Score Stroomranking (Consumentenbond, N&M, WISE)", "4,8 (onvoldoende)", "8,1", "10"],
      ["Herkomst stroom", "33,5% NL groen, 54,5% buitenlandse certificaten, 12% aardgas (mix Essent N.V., 2025)", "97,5% uit Nederlandse bronnen", "100% eigen Nederlandse wind en zon"],
      ["Eigen productie", "Beperkt; moederbedrijf lang actief in kolen", "Eigen wind- en zonneparken, warmtenetten", "Eigen windmolens en zonneparken"],
      ["Kritiekpunt", "Vergroenen met buitenlandse certificaten", "Een deel van de producten vergroend met certificaten", "Klein marktaandeel"],
      ["Klanten", "1,5 miljoen", "1,3 miljoen", "Klein"],
    ],
    [2432, 2400, 2400, 2400], { firstBold: true }));
  out.push(Caption("Tabel 6. Vergelijking van drie leveranciers op duurzaamheid. Bronnen: BNNVARA (z.d.); Energievergelijk (2025); Essent (2025); Greenpeace et al. (2022); Keuze.nl (z.d.); Pure Energie (z.d.-b); WISE (z.d.)."));

  out.push(H2("4.3 Doelstellingen voor \"Nederland van het gas af\""));
  out.push(P("De doelstellingen komen uit het Klimaatakkoord (2019) en de Klimaatwet. In de Klimaatwet staat dat Nederland in 2030 55% minder broeikasgassen moet uitstoten dan in 1990 (oorspronkelijk 49%, in 2021 verhoogd) en in 2050 95% minder. Voor de gebouwde omgeving is dat vertaald naar concrete aantallen (Rijksoverheid, z.d.; RVO, 2022):"));
  [
    "**2030:** 1,5 miljoen bestaande woningen zijn aardgasvrij of aardgasvrij-klaar. Inclusief nieuwbouw gaat het om ongeveer 2,3 miljoen woningen zonder aardgas in 2030.",
    "**2050:** alle ruim 7 miljoen woningen en 1 miljoen andere gebouwen zijn goed geïsoleerd, worden duurzaam verwarmd en zijn van het aardgas af.",
    "**Nieuwbouw:** sinds 1 juli 2018 krijgt nieuwbouw geen gasaansluiting meer (CBS, 2025b).",
    "**Gemeenten:** vrijwel alle gemeenten hebben eind 2021 een Transitievisie Warmte opgesteld waarin staat welke wijken wanneer van het gas gaan (RVO, 2022). Met de Wet collectieve warmte krijgen zij meer regie over warmtenetten (Ministerie van Klimaat en Groene Groei, 2025).",
    "**Woningcorporaties:** tot 2030 willen zij 675.000 woningen isoleren en 450.000 bestaande woningen aardgasvrij maken (RVO, 2022).",
  ].forEach((t) => out.push(Bullet(t)));
  out.push(P("Belangrijk is dat 'van het gas af' niet betekent dat het gasnet verdwijnt. De overheid wil het aardgasverbruik van woningen en gebouwen afbouwen; voor de industrie en voor piekmomenten blijft gas (steeds vaker groen gas of waterstof) voorlopig nodig.", { spacing: { before: 120 } }));

  out.push(H2("4.4 In hoeverre is Nederland van het gas af?"));
  out.push(P("Het CBS meet jaarlijks hoeveel woningen aardgasvrij zijn. In 2024 was 11,2% van de woningen volledig aardgasvrij, tegen 8,7% twee jaar eerder. Daarnaast was 3,7% van de woningen 'bijna aardgasvrij' (hybride, bijvoorbeeld een hybride warmtepomp), tegen 1,5% in 2022. Ruim 18% van de woningen en andere kleinverbruikers heeft geen gasaansluiting meer. Aardgasvrije woningen gebruiken meestal een warmtepomp of een warmtenet. Van de woningen die vanaf 2015 zijn gebouwd, wordt 36% elektrisch verwarmd, en eengezinswoningen (13%) zijn vaker elektrisch verwarmd dan appartementen (5%) (CBS, 2025b)."));
  out.push(table(
    ["Indicator", "2022", "2024", "Doel 2030"],
    [
      ["Woningen volledig aardgasvrij", "8,7%", "11,2%", "1,5 miljoen bestaande woningen (ca. 2,3 miljoen incl. nieuwbouw)"],
      ["Woningen bijna aardgasvrij (hybride)", "1,5%", "3,7%", "–"],
      ["Kleinverbruikers zonder gasaansluiting", "–", "ruim 18%", "–"],
      ["Nieuwbouw vanaf 2015 elektrisch verwarmd", "–", "36% (2023)", "100% nieuwbouw zonder gas (sinds 2018)"],
    ],
    [3232, 1400, 1600, 3400], { firstBold: true }));
  out.push(Caption("Tabel 7. Stand van zaken 'Nederland van het gas af'. Bronnen: CBS (2025b); RVO (2022)."));
  out.push(P("**Conclusie: Nederland ligt ver achter op schema.** Een groei van 8,7% naar 11,2% in twee jaar betekent ongeveer 1,25 procentpunt per jaar, en een groot deel daarvan is nieuwbouw. Om in 2030 1,5 miljoen bestaande woningen van het gas te halen, moeten tussen 2022 en 2030 gemiddeld ruim 187.000 woningen per jaar worden omgebouwd (eigen berekening: 1,5 miljoen gedeeld door acht jaar). Voor warmtenetten ligt het huidige tempo rond 20.000 nieuwe aansluitingen per jaar, terwijl dat tot 2030 naar 50.000 en daarna naar ruim 80.000 per jaar moet (PBL, 2024). Het PBL constateert dat de uitfasering van aardgas gepaard gaat met veel structurele knelpunten, zoals hoge kosten voor bewoners, personeelstekorten en de volle elektriciteitsnetten uit hoofdstuk 3 (PBL, 2024). De hoge gasprijzen van 2022 hebben de vraag naar warmtepompen en isolatie wel versneld. Het doel van 2050 is daardoor niet onmogelijk, maar het tussendoel van 2030 wordt in het huidige tempo niet gehaald."));

  // ---------- 5. Onze organisatie: Enexis
  out.push(H1("5. Onze organisatie: Enexis"));
  out.push(P("In sprint 1 kozen wij Enexis Netbeheer, de regionale netbeheerder van Groningen, Drenthe, Overijssel, Noord-Brabant en Limburg, met ongeveer 3 miljoen aansluitingen en 6.602 medewerkers (Enexis Holding N.V., 2026). In dit hoofdstuk passen we de resultaten van het onderzoek toe op Enexis: wat betekent de energiemarkt voor Enexis, wat kan Enexis doen op het gebied van duurzaamheid, hoe helpt data daarbij, welke privacy-incidenten zijn er in de sector geweest en welke vragen willen wij stellen aan de gastspreker."));

  out.push(H2("5.1 Wat het onderzoek betekent voor Enexis"));
  [
    "**Enexis zit midden in het congestieprobleem.** De vijf provincies van Enexis behoren tot de gebieden waar de wachtlijsten het eerst ontstonden en nog steeds groeien (Solar Magazine, 2026b). Enexis investeert recordbedragen, maar geeft zelf aan dat het de vraag niet kan bijbenen en dat flexibele oplossingen nodig zijn (Enexis Groep, 2026).",
    "**Enexis beheert ook een gasnet dat langzaam leegloopt.** Met 11,2% aardgasvrije woningen gaat de afbouw van gas langzamer dan gepland, maar in sommige nieuwbouwwijken is er al geen gasnet meer. Enexis moet beslissen waar het nog in gasleidingen investeert en waar niet.",
    "**De prijs raakt Enexis indirect.** Enexis verdient niet aan de energieprijs, maar de prijspiek van 2022 heeft de vraag naar zonnepanelen, warmtepompen en thuisbatterijen versneld, en daarmee de druk op het net.",
    "**Enexis verwerkt veel persoonsgegevens.** Slimme-meterdata, aansluitgegevens en storingsmeldingen zijn persoonsgegevens; de AVG is daarmee direct van toepassing op het datavraagstuk uit sprint 1.",
  ].forEach((t) => out.push(Bullet(t)));

  out.push(H2("5.2 Advies: wat kan Enexis doen op het gebied van duurzaamheid?"));
  out.push(P("Enexis produceert zelf geen energie en kan dus niet 'groener inkopen' zoals een leverancier. De duurzaamheidswinst van een netbeheerder zit in het mogelijk maken van de energietransitie: zo veel mogelijk zon, wind, warmtepompen en laadpalen aansluiten met zo min mogelijk nieuwe kabels. Ons advies bestaat uit vier onderdelen die logisch volgen uit hoofdstuk 3 en 4."));
  out.push(H3("Advies 1: voorspel per station en per postcodegebied wanneer het net vol loopt"));
  out.push(P("Enexis publiceert nu een capaciteitskaart die laat zien waar het net vol *is*. Met de kwartierdata van slimme meters, de open data per postcodegebied, de wachtlijst en de weersverwachting kan Enexis voorspellen waar het net over één tot vijf jaar vol *loopt*. Dit sluit aan op onze hypothese uit sprint 1: postcodegebieden met bedrijfsterrein verbruiken het meest, woongebieden gemiddeld en natuurgebieden het minst. Door verbruiksgroei per soort gebied te modelleren kan Enexis investeringen plannen voordat de wachtlijst ontstaat, in plaats van erna."));
  out.push(H3("Advies 2: bied flexibiliteit actief aan in plaats van te wachten"));
  out.push(P("In 2025 speelde Enexis 542 MW aan flexibele capaciteit vrij (Enexis Groep, 2026). Dat kan meer. Met data over het verbruiksprofiel van elke grootverbruiker kan Enexis zelf uitrekenen welke bedrijven op de wachtlijst direct zouden kunnen worden aangesloten met een tijdsgebonden of capaciteitsbeperkend contract, en hen daarvoor gericht benaderen. Dat verkort de wachtlijst zonder extra kabels en voorkomt dat bedrijven zelf dieselgeneratoren plaatsen."));
  out.push(H3("Advies 3: plan de afbouw van het gasnet wijk voor wijk op basis van data"));
  out.push(P("Enexis verzwaart het elektriciteitsnet al wijk voor wijk met de Buurtaanpak (Enexis Groep, 2026). Dezelfde logica geldt voor gas. Door per postcodegebied het percentage woningen zonder gasaansluiting, het aandeel warmtepompen (uit de open data) en de Transitievisie Warmte van de gemeente te combineren, kan Enexis voorspellen in welke wijken het gasnet binnen tien jaar overbodig wordt. Daar hoeven oude leidingen niet meer te worden vervangen, en dat geld kan naar het elektriciteitsnet. Zo helpt data om niet te investeren in infrastructuur die straks wordt afgekoppeld."));
  out.push(H3("Advies 4: gebruik het middagoverschot in plaats van het weg te gooien"));
  out.push(P("Het aantal uren met negatieve stroomprijzen verdubbelt bijna elke twee jaar (Solar Magazine, 2026a). Enexis kan per station meten op welke uren er te veel zon is en die data delen met bedrijven, zodat batterijen, laadpalen en elektrische boilers precies op die momenten worden ingeschakeld. Opslag bij zonneparken (cable pooling) en buurtbatterijen kunnen daardoor sneller een aansluiting krijgen. Dit maakt de stroom groener zonder dat er een kabel bij hoeft."));
  out.push(H3("Hoe data het advies sterker maakt"));
  out.push(table(
    ["Advies", "Benodigde data", "Analyse", "Beslissing die Enexis ermee neemt"],
    [
      ["1. Vol net voorspellen", "Kwartierdata slimme meters (geanonimiseerd), open data kleinverbruik per postcode, wachtlijst, CBS-buurtcijfers, KNMI-weerdata", "Tijdreeksvoorspelling van piekbelasting per station; classificatie van gebieden (bedrijf, wonen, natuur)", "Volgorde en timing van netverzwaringen"],
      ["2. Flexibiliteit aanbieden", "Verbruiksprofielen grootverbruikers, beschikbare capaciteit per uur per station", "Matching: welke klant past met welk contract op welk station", "Welke wachtende klanten direct een flexibel contract krijgen"],
      ["3. Gasnet afbouwen", "Gasaansluitingen per postcode, % zonder gas, % warmtepompen, Transitievisies Warmte, leeftijd leidingen", "Voorspellen van het jaar waarin een wijk aardgasvrij is", "Welke gasleidingen niet meer worden vervangen"],
      ["4. Overschot benutten", "Teruglevering per kwartier per station, uren met negatieve prijzen, zonnepanelen per postcode", "Patroonherkenning van overschotmomenten per gebied", "Waar batterijen en flexibele afnemers het snelst worden aangesloten"],
    ],
    [1900, 2900, 2500, 2332], { firstBold: true }));
  out.push(Caption("Tabel 8. De rol van data in de vier adviezen."));
  out.push(P("Alle vier de adviezen gebruiken data die Enexis al heeft (zie de activiteitentabel uit ons sprint 1-rapport). Het verschil zit in het gebruik: van terugkijken (waar zit het net vol?) naar vooruitkijken (waar loopt het net vol en wat doen we daaraan?). Dat is precies het datavraagstuk dat wij in sprint 1 formuleerden."));

  out.push(H2("5.3 Privacy-incidenten"));
  out.push(P("We hebben eerst gezocht naar privacy-incidenten bij Enexis zelf, met zoektermen als \"Enexis datalek\", \"Enexis Autoriteit Persoonsgegevens\" en \"Enexis slimme meter gegevens gelekt\". We vonden geen gepubliceerd datalek of boete. Enexis heeft wel een procedure voor de meldplicht datalekken en een privacyverklaring, en legt op zijn website uit welke slimme-metergegevens het uitleest en waarvoor (Enexis Groep, z.d.; Enexis Netbeheer, z.d.). Omdat we geen incident bij Enexis konden vinden, hebben we volgens de opdracht een andere organisatie in de Nederlandse energiesector gekozen: Eneco, één van de drie grootste leveranciers. Eneco had twee duidelijk gedocumenteerde incidenten."));
  out.push(H3("Incident 1: inbraak in 1.700 Mijn Eneco-accounts (januari 2021)"));
  out.push(P("Op 7 januari 2021 logden criminelen in op ongeveer 1.700 Mijn Eneco-accounts van particuliere en kleinzakelijke klanten. Zij gebruikten daarvoor e-mailadressen en wachtwoorden die bij datalekken van *andere* websites waren gestolen (credential stuffing). Omdat veel mensen hetzelfde wachtwoord hergebruiken, werkten die combinaties ook bij Eneco. In de accounts waren persoonsgegevens zoals naam, adres en bankrekeningnummer in te zien en mogelijk aan te passen. Eneco sloot Mijn Eneco tijdelijk af, informeerde de 1.700 getroffen klanten per e-mail, waarschuwde uit voorzorg nog 47.000 klanten die in dezelfde periode hadden ingelogd om hun wachtwoord te wijzigen, deed melding bij de Autoriteit Persoonsgegevens en deed aangifte bij de politie (Security.NL, 2021)."));
  out.push(H3("Incident 2: ransomware bij leverancier AddComm (mei 2024)"));
  out.push(P("Tussen 5 en 17 mei 2024 werd AddComm, een bedrijf dat voor organisaties brieven en e-mails naar klanten verstuurt, getroffen door een ransomware-aanval waarbij ook klantgegevens werden gestolen. Eneco waarschuwde zijn klanten; ook Essent, Vattenfall, ABN AMRO, Bol.com, pensioenfondsen, waterbedrijven en gemeenten deden dat (NOS, 2024; Security.NL, 2024a, 2024b). Voor Eneco was niet precies duidelijk welke gegevens waren buitgemaakt; bij andere organisaties ging het om namen, adressen en klantnummers. Klanten werd gevraagd brieven en e-mails uit naam van Eneco extra goed te controleren en geen persoonlijke gegevens te delen, vanwege het risico op phishing. Dit incident laat zien dat een datalek bij een leverancier in de keten (een 'verwerker') een datalek van de energieleverancier zelf is."));

  out.push(H2("5.4 Hoe de AVG op deze incidenten van toepassing is"));
  out.push(P("De Algemene verordening gegevensbescherming (AVG; Verordening (EU) 2016/679) geldt voor iedere organisatie die persoonsgegevens van mensen in de EU verwerkt. Naam, adres, e-mailadres, bankrekeningnummer, klantnummer en energieverbruik zijn persoonsgegevens (artikel 4). Hieronder staat per artikel hoe de AVG op de twee incidenten van toepassing is."));
  out.push(table(
    ["AVG-artikel", "Wat het artikel eist", "Incident 1: Mijn Eneco (2021)", "Incident 2: AddComm (2024)"],
    [
      ["Art. 5: beginselen (integriteit en vertrouwelijkheid, dataminimalisatie)", "Gegevens moeten passend beveiligd zijn en er mogen niet meer gegevens worden verwerkt dan nodig.", "Bankrekeningnummers waren zichtbaar in een klantportaal dat alleen met wachtwoord was beveiligd.", "Een externe partij had toegang tot grote hoeveelheden klantgegevens voor het versturen van post."],
      ["Art. 24 en 32: passende technische en organisatorische maatregelen", "Beveiliging moet passen bij het risico, bijvoorbeeld tweefactorauthenticatie, het blokkeren van verdachte inlogpogingen en versleuteling.", "Credential stuffing is een bekend risico; de vraag is of Eneco voldoende maatregelen had (zoals het herkennen van duizenden inlogpogingen vanaf één bron).", "Eneco moet controleren of AddComm voldoende beveiligd was; ransomware is een bekend risico."],
      ["Art. 28: verwerker en verwerkersovereenkomst", "Als een organisatie een ander bedrijf gegevens laat verwerken, blijft zij zelf verantwoordelijk en moet zij afspraken over beveiliging vastleggen.", "Niet van toepassing: Eneco verwerkte zelf.", "Direct van toepassing: AddComm is verwerker, Eneco (en Essent, Vattenfall) blijven verwerkingsverantwoordelijke."],
      ["Art. 33: melding bij de Autoriteit Persoonsgegevens binnen 72 uur", "Een datalek met risico voor betrokkenen moet binnen 72 uur worden gemeld.", "Eneco meldde het lek bij de AP en deed aangifte.", "De getroffen organisaties meldden het lek; de verwerker moet de verantwoordelijke direct informeren (art. 33 lid 2)."],
      ["Art. 34: informeren van betrokkenen", "Bij een hoog risico moeten de betrokkenen zelf worden geïnformeerd.", "1.700 klanten geïnformeerd en 47.000 uit voorzorg gewaarschuwd.", "Klanten gewaarschuwd voor phishing en gevraagd om post te controleren."],
      ["Art. 83: boetes", "De AP kan boetes opleggen tot € 20 miljoen of 4% van de wereldwijde jaaromzet.", "Voor zover bekend geen boete; de snelle melding en communicatie werken verzachtend.", "Voor zover bekend geen boete."],
    ],
    [2100, 2500, 2516, 2516], { firstBold: true, size: 17 }));
  out.push(Caption("Tabel 9. Toepassing van de AVG op de twee incidenten bij Eneco. Bronnen: Verordening (EU) 2016/679 (2016); NOS (2024); Security.NL (2021, 2024a, 2024b)."));
  out.push(P("**Wat Enexis hiervan kan leren.** Voor een netbeheerder is de AVG minstens zo belangrijk als voor een leverancier. Enexis leest slimme meters uit en kan daarmee in principe zien wanneer iemand thuis is; daarom mag Enexis die gegevens alleen gebruiken voor wettelijke taken en moet de klant toestemming geven voor gedetailleerde uitlezing (Enexis Netbeheer, z.d.). In de open data per postcodegebied neemt Enexis daarom alleen rijen op met minimaal tien aansluitingen, zodat losse huishoudens niet herkenbaar zijn (zie ons sprint 1-rapport). Voor de adviezen in paragraaf 5.2 betekent dit dat de analyses met geaggregeerde of gepseudonimiseerde data moeten worden uitgevoerd, dat met externe partijen (bijvoorbeeld een data-consultant zoals wij) een verwerkersovereenkomst nodig is en dat een datalek binnen 72 uur bij de AP gemeld moet worden."));

  out.push(H2("5.5 Vragen voor de gastspreker"));
  out.push(P("Op basis van dit onderzoek hebben we zes vragen voorbereid voor de gastspreker. Bij elke vraag staat waarom die relevant is voor onze opdracht."));
  out.push(table(
    ["Nr", "Vraag", "Waarom relevant voor onze opdracht"],
    [
      ["1", "Hoe bepaalt uw organisatie welke klant op de wachtlijst als eerste transportcapaciteit krijgt, en welke data gebruikt u daarbij?", "Eind 2025 stonden 15.014 bedrijven op de wachtlijst voor afname (Duurzaam Ondernemen, 2026). Onze datavragen 2 en 4 uit sprint 1 gaan over het voorspellen van capaciteitsproblemen; we willen weten welke data hiervoor nu al wordt gebruikt."],
      ["2", "Hoe ver vooruit kunt u nu voorspellen waar een station vol loopt, en welke datasets ontbreken nog om dat beter te doen?", "Ons advies 1 is om van terugkijken naar vooruitkijken te gaan. We willen toetsen of onze aanname klopt dat slimme-meterdata en open data per postcode daarvoor voldoende zijn."],
      ["3", "Welke gegevens van slimme meters mag u gebruiken voor analyses, en hoe anonimiseert of aggregeert u die om aan de AVG te voldoen?", "Slimme-meterdata zijn persoonsgegevens (Verordening (EU) 2016/679, art. 4). Voor ons datavraagstuk moeten we weten met welke data we wel en niet mogen werken."],
      ["4", "Wanneer besluit u een gasleiding in een wijk niet meer te vervangen omdat de wijk aardgasvrij wordt, en hoe zeker is die voorspelling?", "In 2024 was 11,2% van de woningen aardgasvrij (CBS, 2025b). Advies 3 gaat over het datagedreven afbouwen van het gasnet; we willen weten of dit in de praktijk al gebeurt."],
      ["5", "Hoe meet u het effect van flexibele contracten en batterijen (zoals de 542 MW die Enexis in 2025 vrijspeelde) en wat is het maximum dat haalbaar is?", "Enexis stelt dat flexibele oplossingen de toekomst zijn (Enexis Groep, 2026). Dit bepaalt of advies 2 realistisch is."],
      ["6", "Hoe werkt u samen met TenneT en met leveranciers op momenten van negatieve stroomprijzen, en wie beslist dan dat zonneparken worden teruggeschakeld?", "Nederland had in 2025 een record van 581 uren met negatieve prijzen (Solar Magazine, 2026a). Dit raakt de overcapaciteit uit hoofdstuk 3 en advies 4."],
    ],
    [500, 4300, 4832], { size: 17 }));
  out.push(Caption("Tabel 10. Vragen voor de gastspreker met onderbouwing."));

  // ---------- 6. Conclusies
  out.push(H1("6. Conclusies"));
  out.push(P("De hoofdvraag van deze sprint was: \"Onderzoek de Nederlandse energiemarkt\". We beantwoorden die aan de hand van de deelvragen uit hoofdstuk 1."));
  out.push(P("**De markt is strak verdeeld in netbeheerders en leveranciers.** Twee landelijke en zes regionale netbeheerders hebben een wettelijk monopolie op het transport en staan onder toezicht van de ACM; ongeveer vijftig leveranciers met een vergunning concurreren om de klant, waarbij Vattenfall, Essent en Eneco samen het grootste deel van de markt hebben. Enexis is als netbeheerder dus geen concurrent van de leveranciers, maar is wel afhankelijk van wat zij en hun klanten doen."));
  out.push(P("**De prijs van energie wordt grotendeels buiten de leverancier bepaald.** Van de energierekening gaat een deel naar de leverancier (levering), een deel naar de netbeheerder (vast transporttarief) en een groot deel naar de overheid (energiebelasting en btw). In 2022 verdubbelde het variabele leveringstarief voor gas van € 1,20 naar € 2,78 per m³ en voor elektriciteit van € 0,32 naar € 0,66 per kWh. De oorzaak lag vrijwel volledig bij de Russische inval in Oekraïne en het dichtdraaien van Nord Stream 1; de stroomprijs volgde de gasprijs omdat gascentrales de prijs zetten. De overheid dempte de klap met een btw-verlaging, lagere energiebelasting, een korting van € 190 en een prijsplafond."));
  out.push(P("**Over- en ondercapaciteit bestaan tegelijk.** Ruim 15.000 bedrijven wachten op een aansluiting en bijna 8.700 op capaciteit om terug te leveren, terwijl Nederland in 2025 een record van 581 uren met negatieve stroomprijzen had. Het probleem speelt het sterkst in de provincies van Enexis (Groningen, Drenthe, Overijssel, Noord-Brabant en Limburg) en in Gelderland, Flevoland en Utrecht. Netbeheerders verzwaren het net (Enexis: € 1,9 miljard in 2025), maar lossen het vooral op met congestiemanagement, flexibele contracten, batterijen en het terugschakelen van zon en wind; leveranciers sturen met dynamische contracten en terugleverkosten."));
  out.push(P("**De duurzaamheidsontwikkelingen versterken elkaar, en de druk op het net.** De helft van de elektriciteit is al hernieuwbaar, wind op zee groeit naar 21 GW, groen gas wordt vanaf 2027 verplicht bijgemengd en de warmtetransitie verschuift de vraag van gas naar elektriciteit. Leveranciers verschillen sterk: Pure Energie levert alleen eigen Nederlandse wind en zon (een 10), Eneco doet het goed voor een grote partij (8,1) en Essent vergroent nog grotendeels met buitenlandse certificaten (4,8). Nederland ligt ver achter op het doel van 1,5 miljoen aardgasvrije woningen in 2030: in 2024 was 11,2% van de woningen aardgasvrij."));
  out.push(P("**Voor Enexis zit de duurzaamheidswinst in data.** Enexis kan niet groener inkopen, maar kan de energietransitie wel versnellen door met slimme-meterdata, open data per postcode en de wachtlijst te voorspellen waar het net vol loopt, flexibiliteit actief aan te bieden, de afbouw van het gasnet wijk voor wijk te plannen en het middagoverschot te benutten. Alle benodigde data heeft Enexis al; de stap is van terugkijken naar vooruitkijken."));
  out.push(P("**Privacy is daarbij geen bijzaak.** De incidenten bij Eneco (credential stuffing in 2021 en de ransomware-aanval bij verwerker AddComm in 2024) laten zien dat de AVG eist dat gegevens passend beveiligd zijn (art. 32), dat een organisatie verantwoordelijk blijft voor haar verwerkers (art. 28) en dat een lek binnen 72 uur bij de AP wordt gemeld en betrokkenen worden geïnformeerd (art. 33 en 34). Voor het datavraagstuk van Enexis betekent dit dat analyses op geaggregeerde of gepseudonimiseerde data moeten worden uitgevoerd. Met deze domeinkennis kunnen wij in de volgende sprint de data van Enexis beoordelen op wat logisch is en wat niet, precies het doel van *business understanding*."));

  return out;
};
